export const GET_QUOTES = 'GET_QUOTES';
export const GET_ADDONS = 'GET_ADDONS';
export const SELECT_THIS_EXTRA = 'SELECT_THIS_EXTRA';
export const TOGGLE_PRICE_VIEW = 'TOGGLE_PRICE_VIEW';
export const REMOVE_EXTRA_ADDON = 'REMOVE_EXTRA_ADDON';